### PR TITLE
Detailed build steps. Not everyone is familiar enough with cmake.

### PR DESCRIPTION
**Pull request by cvogt**

### CODE REVIEW

**Comment by blizzard4591** [comment]
Nice!
I do not have access to Mac OS and therefore have no experience on what is necessary to build there. Your contribution is very welcome!

A few notes before we can merge:
 - Please change your script to create a "build" folder either inside of the source tree or outside of it, but "cmake ." is highly discouraged, as it clutters the source with build files. I will add similar information to the general build information.
 - You write "./openMittsu <args see below>", but afaik there are no command line arguments, aside from a view general commands for Qt. If you refer to LIBSODIUM_INCLUDE_DIRS et. al., then these need to be passed to cmake like so: "cmake .. -DLIBSODIUM_INCLUDE_DIRS=/some/path"
- Could "OSX view brew" be a typo? If you did not mean "OSX through brew" I do not get what that means.

**Comment by cvogt** [comment]
@blizzard4591 
> Please change your script to create a "build" folder either inside of the source tree or outside of it, but "cmake ." 

How do I do this? It is the first time I used cmake.

yeah, typo

**Comment by blizzard4591** [comment]
I am so sorry! It is so easy to forget that it took me months to figure this stuff out, too, and that not everybody uses this often.

My typical approach is the following:

- Go into my projects folder, e.g. `cd Projects`
- Check out the repository: `git checkout https://github.com/blizzard4591/openMittsu.git`. The repo now resides in Projects/openMittsu.
- Go into the Repository: `cd openMittsu`
- Create a folder that will contain all generated files from a build: `mkdir build`. Note that this folder can reside anywhere, even outside of the repository, so Projects/openMittsuBuildFolder would also be acceptable.
- Switch to the build folder: `cd build`
- Call CMake with Options as applicable, e.g.: `cmake .. -DOPENMITTSU_DEBUG=On`. If you need something other than standard Makefiles, for example an XCode solution, use `cmake .. -G Xcode` followd by other options. Note that the `..` stands for "one directory up" and needs to point to the folder containing the CMakeList.txt file, e.g. Projects/openMittsu in this example. You can use a fully qualified path, but you do not need to. For other Generators, see https://cmake.org/cmake/help/v3.0/manual/cmake-generators.7.html
- Compile: `make -j 4`, where -j enables multi-threaded compiling, in this case with 4 threads.

By using a separate build folder, you can (a) build different binaries from the same sources without having to re-configure everything and (b) simply purge the build directory to force a clean rebuild without having to hand-pick the source tree clean.

I hope this helps!

**Comment by cvogt** [comment]
added the info. You also might want to put the entire description you gave somewhere visible :).

It also took me forever to find the information needed for my contacts.ini file. Finally found it in the backup. Added it to the docs as well now.

**Comment by blizzard4591** [comment]
Sorry for the delay - I am currently very busy, but I will pick this (and other changes) up in mid-december.
If not, PM me until I do ;)

**Pull request merged**
